# Generated by Django 6.0.2 on 2026-02-25 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_slide_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Атрибут варианта',
                'verbose_name_plural': 'Атрибуты вариантов',
            },
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_slug_42f8f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_sku_a1eae6_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_categor_9c2292_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='core.productattributevalue', verbose_name='Значение атрибута'),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='core.productvariant', verbose_name='Вариант'),
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AlterUniqueTogether(
            name='productvariantattribute',
            unique_together={('variant', 'attribute_value')},
        ),
    ]
