# Generated by Django 6.0.2 on 2026-02-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productvariantattribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram ник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка на покупку',
                'verbose_name_plural': 'Заявки на покупку',
                'ordering': ['-created_at'],
            },
        ),
    ]
