# Generated by Django 6.0.2 on 2026-03-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views_count',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, help_text='Вставляйте текст в формате:\nВид оборудования: Пищевое\nВид пищевого оборудования: Нейтральное\n...', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (можно вставить характеристики)'),
        ),
    ]
