# Generated by Django 6.0.2 on 2026-03-20 23:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_brand_remove_product_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
